build:
  image: framgia/laravel-workspace
  commands:
    - sleep 60
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - composer install
    - npm install
    - gulp
    - cp .env.testing .env
    - php artisan migrate --database=mysql_test
    - vendor/bin/phpunit
compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
deploy:
  rocketeer:
    image: fdplugins/rocketeer:php5
    when:
      branch: develop
    commands:
      - rocketeer deploy --stage=staging --no-interaction
  rocketeer:
    image: fdplugins/rocketeer:php5
    when:
      branch: master
    commands:
      - rocketeer deploy --stage=production --branch=master --no-interaction
notify:
  chatwork:
    image: fdplugins/chatwork
    room_id: $$CHATWORK_ROOM_ID
    token: $$CHATWORK_TOKEN
cache:
  mount:
    - .git
    - vendor
    - node_modules
